version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: demo_park
        MYSQL_USER: my_docker
        MYSQL_PASSWORD: my_docker
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql